[package]
name = "axruntime"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
alloc = ["axalloc"]
paging = ["alloc", "axhal/paging"]

log-level-off = ["axlog/log-level-off"]
log-level-error = ["axlog/log-level-error"]
log-level-warn = ["axlog/log-level-warn"]
log-level-info = ["axlog/log-level-info"]
log-level-debug = ["axlog/log-level-debug"]
log-level-trace = ["axlog/log-level-trace"]

platform-qemu-virt-riscv = ["axhal/platform-qemu-virt-riscv"]

default = []

[dependencies]
axalloc = { path = "../axalloc", optional = true }
axconfig = { path = "../axconfig" }
axhal = { path = "../axhal" }
axlog = { path = "../axlog" }
