[workspace]

members = [
    "crates/crate_interface",
    "crates/page_table",

    "modules/axalloc",
    "modules/axconfig",
    "modules/axhal",
    "modules/axruntime",

    "os/helloworld",
    "os/memtest",
]
