[package]
name = "axhal"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
platform-qemu-virt-riscv = ["axconfig/platform-qemu-virt-riscv"]
paging = ["axalloc", "page_table"]
default = []

[dependencies]
log = "0.4"
cfg-if = "1.0"
bitflags = "1.3"
axconfig = { path = "../axconfig" }
axalloc = { path = "../axalloc", optional = true }
page_table = { path = "../../crates/page_table", optional = true }

[target.'cfg(any(target_arch = "riscv32", target_arch = "riscv64"))'.dependencies]
riscv = "0.10"
sbi-rt = { version = "0.0.2", features = ["legacy"] }

[build-dependencies]
axconfig = { path = "../axconfig" }
